//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityPracticeWork.Models
    {
    using System.Data.Entity;

    public partial class UserDataEntities : DbContext
    {
    //    public UserDataEntities()
    //        : base("name=UserDataEntities")
    //    {
    //    }
    
    //    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    //    {
    //        throw new UnintentionalCodeFirstException();
    //    }
    
    //    public virtual DbSet<person> people { get; set; }
    //    public virtual DbSet<rank> ranks { get; set; }
    //    public virtual DbSet<regiment> regiments { get; set; }
  }
}
