//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityPracticeWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int person_Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string NI { get; set; }
        public int? Regiment_ID { get; set; }
        public int? Rank_ID { get; set; }
    }
}
