//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityPracticeWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class regiment
    {
        public int reg_id { get; set; }
        public string regiment_name { get; set; }
    }
}
